- name: Ansible Playbook to Create all the RoboShop Project Jobs in Jenkins Server.
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - APP-SETUP-WITH-ANSIBLE
      - Infrastructure
    pipeline_jobs:
      - { jobName: "roboshop", folderName: "APP-SETUP-WITH-ANSIBLE", repoName: "roboshop-ansible"}
      - { jobName: "cart", folderName: "Infrastructure", repoName: "cart-infra"}
      - { jobName: "catalogue", folderName: "Infrastructure", repoName: "catalogue-infra"}
      - { jobName: "user", folderName: "Infrastructure", repoName: "user-infra"}
      - { jobName: "frontend", folderName: "Infrastructure", repoName: "frontend-infra"}
      - { jobName: "payment", folderName: "Infrastructure", repoName: "payment-infra"}
      - { jobName: "shipping", folderName: "Infrastructure", repoName: "shipping-infra"}
